name: Tests Python

on:
  push:
    # branches: [ main, master, v5 ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Docker Compose
        run: docker compose version

      - name: Build et démarrage
        run: docker compose up --build -d

      - name: Lancer les tests avec couverture 80%
        run: docker compose exec -T planning-api pytest --cov --cov-report=term-missing --cov-fail-under=80

      - name: Logs si échec
        if: failure()
        run: docker compose logs planning-api

      - name: Arrêter les conteneurs
        if: always()
        run: docker compose down -v
